language: node_js
branches:
  only:
    - master
    - beta
cache: pnpm
notifications:
  email: false
node_js:
  - node
  - 'lts/*'
script:
  - pnpm test:prod && pnpm build
after_success:
  - pnpm run report-coverage
  - pnpm run deploy-docs
