name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup mise
        uses: jdx/mise-action@v3
        with:
          install: true
          cache: true

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm exec lefthook run ci --job lint

      - name: Typecheck
        run: pnpm exec lefthook run ci --job typecheck

      - name: Test & Coverage
        run: pnpm exec lefthook run ci --job "test coverage"

      - name: Build Library
        run: pnpm exec lefthook run ci --job "build library"

      - name: Build Docs
        run: pnpm exec lefthook run ci --job "build docs"

      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          working-directory: .

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/out

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
